### PR TITLE
Jquery svg

### LINKED ISSUE #173: jQuery does not support camelCase attributes used by SVG
camelCase attribute names are pretty rare, but the SVG spec does call for it.

For example `startOffset` https://www.w3.org/TR/SVG/text.html#TextPathElementStartOffsetAttribute

Using the standard approach the attributes are lower-cased automatically, e.g. this fails:

```clojure
(textPath :xlink/href "#my-curve" :startOffset "25%" "foo")
; <textPath href="#my-curve" startoffset="25%">foo</textPath>
```

The only way I could get this to do what I wanted was with an awkward `with-let` wrapper like:

```clojure
(with-let [el (text-path :xlink/href "#my-curve" "foo")]
 (.setAttribute el "startOffset" "15%"))
; <textPath href="#my-curve" startOffset="25%">foo</textPath>
```

I think this SO post is relevant: https://stackoverflow.com/questions/26457455/setting-attribute-value-of-an-element-in-camelcase-using-a-directive

### PR DESCRIPTION
**Pull request by thedavidmeister**
fixes #173

### CODE REVIEW

**Comment by flyboarder** [comment]
do we need both testing systems?

**Comment by thedavidmeister** [comment]
@flyboarder i'd like to deprecate the selenium based setup and move forward with the cljs one as it is much lower overhead and more robust too.

i didn't want to pollute this PR with reimplementing the existing tests in doo though

**Comment by thedavidmeister** [comment]
@flyboarder here's a followup for the testing side of things https://github.com/hoplon/hoplon/issues/191

**Comment by flyboarder** [comment]
I'll merge this, the SVG fix is confirmed and the changes to cljs testing should continue to develop.

**Pull request merged**
