### PR TITLE
Queue pending when-dom event handlers

### PR DESCRIPTION
**Pull request by micha**

### CODE REVIEW

**Comment by thedavidmeister** [comment]
@micha looks good, can we add the test that we discussed last night?

**Comment by thedavidmeister** [comment]
we should expect something like this to pass now:

```
(deftest bind-events
 (let [c (j/cell nil)
       f #(reset! c true)
       i (h/div :click f)]
   (-> js/document .-body (.appendChild i))
   (with-dom i
    ; Native event.
    (is (nil? @c))
    (.dispatchEvent i (js/Event. "click"))
    (is (= true @c)))))
```

**Comment by micha** [comment]
ah right, I'll add the test to this pr

**Comment by thedavidmeister** [comment]
@micha i just disabled circle from watching hoplon FYI, as I wasn't exactly sure where that part of the other PR stood.

Ping me if you want to discuss that :)

**Pull request merged**
