### PR TITLE
WIP on native fallbacks for prototype fns

### LINKED ISSUE #197: calling hoplon.core/body from phantomjs throws an error
I see this if i call `hoplon.core/body` from any test:

`#object[TypeError TypeError: null is not an object (evaluating 'this$.hoplonKids = null')]`

### LINKED ISSUE #203: strange issues with whitespace editing crashing ckeditor5
cross posting this from the ckeditor5 issue queue:

https://github.com/ckeditor/ckeditor5/issues/706

so far it only seems to happen in hoplon, not a "vanilla" JS implementation.

### PR DESCRIPTION
**Pull request by thedavidmeister**
fixes #203 
fixes #197 

followups:

#206 
#207 
#208 
#209 
#210 
#211

### CODE REVIEW

**Comment by thedavidmeister** [comment]
so this PR fixes the issues i was seeing in ckeditor.

outstanding q's i have:
- is checking for the existence of `.-hoplonKids` really a robust test for "is a hoplon element"?
-- i had expected to see something right at the moment of element creation, e.g. in `mkelem`
- is checking just the native-ness of children enough, or does the parent need to be checked also?
-- could bypassing hoplon's management of a hoplon-el parent break accounting downstream?
- why did things break in the first place? there must be some inconsistency in behaviour between native prototype fns and hoplon's replacments (nodes vs. elements?)
- how to test this?

**Comment by thedavidmeister** [comment]
`ensure-kids!` is the only thing that sets `hoplonKids` and this is called only by these prototype fns, which almost always call it - even for native elements.

**Comment by thedavidmeister** [comment]
Note to self:
[ ] tests for managed/unmanaged `appendChild`
[ ] test for `.removeChild` in `appendChild`
[ ] test for `hoplonKids` containing correct data when managed append follows unmanaged append
[ ] tests for managed/unmanaged `removeChild`
[ ] tests for managed/unmanaged `insertBefore`
[ ] tests for managed/unmanaged `replaceChild`
[ ] tests for managed/unmanaged `setAttribute`

**Comment by thedavidmeister** [comment]
not going to touch `set-setAttribute!` at this stage as it is only associated with the experimental `elem+` macro and not used on the `js/Element` prototype.

**Comment by flyboarder** [comment]
@thedavidmeister so in my testing, only the `set-appendChild` breaks tpl tests, possibly suggesting that most of this is unneeded.

**Comment by flyboarder** [comment]
On a side note, I tracked down the prototype overrides to 6.0.0-alpha2/alpha5, somewhere in there they were added which is while the protocol was being introduced. These are ancient black magics.

**Pull request merged**
