### PR TITLE
Add for=, if=, when=, cond=, and case=

### PR DESCRIPTION
**Pull request by micha**
Is it good?

### CODE REVIEW

**Comment by levitanong** [comment]
Omg @micha I didn't know `delay` was a thing!!! Now I need to use it on all the things!

**Comment by levitanong** [comment]
@micha do you think it's possible to implement some of the appendChild stuff on a Delay object? That would allow us to do
```clojure
(cell= (if pred? (delay consequent) (delay alt)))
```

**Comment by micha** [comment]
@levitanong I think you'd still need to create the Delay objects outside the cell, otherwise it would create new ones each time the formula is evaluated, no?

**Comment by levitanong** [comment]
@micha Oh right! Silly me. :smile: In that case, I think the `if=` implementation is definitely cleaner and better than the `if-tpl` one. +1!

**Comment by dm3** [comment]
Should we then remove `if-tpl` and `switch-tpl` that got merged into master earlier with this PR then?

**Pull request merged**
