### PR TITLE
7.1 Proposal

### PR DESCRIPTION
**Pull request by flyboarder**
This PR includes all the proposed changes for Hoplon 7.1

Supersedes #181 #183 #185

_**NOTE: DO NOT MERGE UNTIL REVIEW**_

### CODE REVIEW

**Comment by flyboarder** [comment]
I would like to update `boot-cljs` to `2.1.2` however I believe this needs fixing from https://github.com/crisptrutski/boot-cljs-test

**Comment by thedavidmeister** [comment]
I get errors

```
(h/defelem section
 [{:keys [left right middle]} children]
```

`clojure.lang.ExceptionInfo: clojure.lang.ExceptionInfo: ERROR: Call to hoplon.core/elem did not conform to spec:`

**Comment by thedavidmeister** [comment]
i'm going to rollback the clojure version until https://github.com/bensu/doo/issues/146 lands

**Comment by flyboarder** [comment]
This is probably ready now, waiting on Clojure 1.9 to land.

**Comment by flyboarder** [comment]
Still working with Clojure 1.9 and Boot 2.7.2

**Pull request merged**
