### PR TITLE
test and fix for events not being bound for js elements with on!

### LINKED ISSUE #153: can't test events bound with `on!` using cljs tests
```
(deftest input-fn
  (async done
    (let [c (j/cell nil)
          f #(reset! c true)
          i (h/input :click f)
          e (.createEvent js/document "HTMLEvents")]
      (.initEvent e "click" true false)
      (is (nil? @c))
      (.dispatchEvent i e)
      (h/with-timeout 0 (do (is (= true @c))
                            (done))))))
```
I expect this to pass but it doesn't, `when-dom` in the `on!` multimethod seems like a likely culprit as it explicitly checks that the element is in the js document before binding the event.

Do we really need to wait for the element to be in the DOM before binding an event?

### PR DESCRIPTION
**Pull request by thedavidmeister**
fixes #153 

This should make it possible to handle events with `on!` for elements that aren't necessarily going to be added to `js/document`

So there's a bit going on here, more than I would ideally like in a single PR...

- Added https://github.com/crisptrutski/boot-cljs-test to the repo so we could run cljs tests through phantom (or whatever) in a unit test style environment instead of selenium talking to a browser
- Wrote roughly equivalent tests in a browser context and unit test context to show that we can bind a click event to an element both detached and attached to a document
- Travis wasn't actually running the browser tests! this is bad. Tried CircleCI instead. You can see a build where Travis would pull down deps but then just exit with 0 instead of running browser tests here - https://travis-ci.org/hoplon/hoplon/builds/173163540 - compare this to a CircleCI build with the `boot test` task working - https://circleci.com/gh/hoplon/hoplon/5
- Added a boot task `develop-cljs-tests` that mirrors `develop-tests` but for the cljs unit tests
- Modified `on!` everywhere to not use `when-dom` any more

Of course, whoever accepts this PR will need to disable Travis as a required integration on Github and add Circle in it's place.

### CODE REVIEW

**Comment by flyboarder** [comment]
Looks good!

**Comment by flyboarder** [comment]
@thedavidmeister can we close this or are there parts that need to be split out and rebased?

**Comment by thedavidmeister** [comment]
@flyboarder there's a few things here:

- travis is irrelevant now, we can safely ditch that
- selenium is gone too, we're using direct cljs tests now
- the boot tasks already have equivalents merged in 7.1
- the modifications to `on!` are still unresolved though, see #153  for the full story

cliffnotes are:

```
micha [1:45 AM]
are you sure the when-dom really isn't necessay?

thedavidmeister [1:45 AM]
i don’t know why it was there in the first place

micha [1:46 AM]
it was there because certain events couldn't be added until the element was in the dom

thedavidmeister [1:46 AM]
ok, well if you can remember what events they are

[1:46]
we can update the test easy

micha [1:46 AM]
i do not 😕
```

so this ended up in a bit of a stalemate unfortunately :(

I personally believe the `when-dom` adds unnecessary additional complexity by introducing async behaviour for event binding and making it hard to test detached DOM elements (the default state for any new element created by Hoplon in unit tests).

@micha  is concerned that some event/browser combos don't handle event binding correctly for detached elements, but cannot remember specifics and we don't have tests/docs available for this

anecdotally, i have overridden `on!` in my own projects in the way proposed here and haven't run into any problems yet, but i cannot claim to be comprehensively testing event/browser combos either.

**Comment by flyboarder** [comment]
Let’s remove the `when-dom` in `7.2` this makes testing easier and will cause any browser issues to emerge if they are still present. We can then solve for those cases, many of which were probably old IE versions.

**Comment by thedavidmeister** [comment]
@flyboarder ok, well it needs to be cleaned up then - i can look at this as part of the 7.2 work being done.

it does highlight the point that we don't test across a lot of browsers with the tests we have though.

**Comment by flyboarder** [comment]
Fixed in latest `7.2-SNAPSHOT`.

**Pull request closed without merging**
