### PR TITLE
Regex-tpl

### PR DESCRIPTION
**Pull request by flyboarder**
Added `regex-tpl` this can be used for simple page routing based on regex.

### CODE REVIEW

**Comment by flyboarder** [comment]
This is a cross between `case-tpl` signature and  `cond-tpl` functionality.
Cases are a regex pattern which is wrapped in `cell=`  and `re-matches`.

**Comment by thedavidmeister** [comment]
FYI, you could also use something like https://github.com/gf3/secretary

**Comment by flyboarder** [comment]
@thedavidmeister secretary is what I was using before, but I felt there was a simple solution with `route-cell`.

Here is the full setup:
```clojure
(def route (route-cell "#"))
```
A `dispatch!` alternative: 
```clojure
(defn route!
  "Change URL hash, does not reload the page."
  [& route] (aset js/window "location" "hash" (korks->str route)))
```

```clojure
(html
   (head)
   (body
      (regex-tpl route
         #"#" (landing)
         #"#dash" (dashboard)
         :else (404))))
```

I was thinking of making a `route-tpl` which wraps a dynamically bound `route-cell` to get rid of some boilerplate. This would be an easy include for a simple routing system within hoplon.

**Comment by flyboarder** [comment]
Some addon's to the above for extended routing capabilities

```clojure
(defn re-korks 
   "Converts korks to regex pattern."
   [& korks]
   (re-pattern (korks->str korks)))

(defn route-matches [route & korks]
  (re-matches (re-korks korks) (str route)))

(defc= route-current 
   "Returns a vector of the current path converted to korks."
   (mapv keyword (rest (s/split route #"/"))))
```
Can be used like so:
```clojure
(defc= dash?
  "Returns true if URL hash matches #/dash/*"
  (route-matches route :dash :* ))
```

**Comment by thedavidmeister** [comment]
@flyboarder i do like the idea of a route tpl, i also like the way that secretary supports key/value parameters as well.

I also put up some code at https://github.com/hoplon/hoplon/wiki/Pages-and-routes that i'm looking for some feedback on.

Maybe there's a way we can combine it all together?

**Comment by flyboarder** [comment]
@thedavidmeister I was skimming that yesterday, looks good! Key/Value params was a thought of mine, should be pretty simple to implement.

**Comment by micha** [comment]
i like the idea of using bidi to construct the route parsing functions then using that in a formula cell with the hoplon core route-cell cell. the coil thing about bidi vs secretary or regex is that it's bi-directional, the same expression created link generating functions as well, and it doesn't do anything other than parse and emit

**Comment by flyboarder** [comment]
@micha I like your idea of using bidi, I think this will fit in nicely with the `case-tpl` where it can match against the handler. Thanks for the suggestion, I have a new thing to try now. 👍

**Comment by flyboarder** [comment]
@thedavidmeister @micha Using micha's bidi suggestion this is what I came up with...

```clojure
(ns degree9.routing
  (:require [bidi.schema :refer [RoutePair]]
            [schema.core :as schema]
    #?@(:cljs
         [[cuerdas.core :as s]
          [bidi.bidi :refer [match-route path-for]]
          [hoplon.core :refer [route-cell]]]))
  #?(:cljs
      (:require-macros [degree9.routing :refer [route-tpl]])))

#?(:cljs
    (def ^:dynamic *route* (route-cell "")))

#?(:cljs
    (defn wrap-route [routes routec]
      (javelin.core/cell= (:handler (match-route routes (s/strip-prefix routec "#"))))))

#?(:cljs
    (defn route!
      "Change URL hash, does not reload the page."
      [routes & routeopts]
      (aset js/window "location" "hash"
        (s/join ["#" (apply path-for routes routeopts)]))))

#?(:clj
    (defmacro route-tpl
      [routes & clauses]
      (assert (even? (count clauses)))
      `(let []
        (schema/validate RoutePair ~routes)
        (hoplon.core/case-tpl (wrap-route ~routes *route*) ~@clauses))))
```

**Comment by thedavidmeister** [comment]
ok, bidi sounds cool too. Could we update the wiki with some examples? https://github.com/hoplon/hoplon/wiki/Pages-and-routes

**Comment by micha** [comment]
The default case does not need to be a keyword like this:

```clojure
(regex-tpl route
  #"^/foo/" (foo-view)
  #"^/bar/" (bar-view)
  :else     (default-view))
```

It could be just a regex that matches anything:

```clojure
(regex-tpl route
  #"^/foo/" (foo-view)
  #"^/bar/" (bar-view)
  #".*"     (default-view))
```

Also we could make the name shorter if we wanted to: `re-tpl` perhaps?

**Comment by micha** [comment]
We could also possibly expose the match result as a cell like `*match*`:

```clojure
(regex-tpl route
  #"^/foo/([^/]+)/([^/]+)/?$" (cell-let [[_ bar baz] *match*]
                                (foo-view :bar bar :baz baz))
  ...
```

**Comment by flyboarder** [comment]
Closing as there are many options now for routing with hoplon.
hoplon/brew has a few now also.

**Comment by thedavidmeister** [comment]
yes, i'm using bidi now as well, with `goog.History` :) https://github.com/thedavidmeister/wheel/blob/master/src/wheel/route/core.cljs

**Pull request closed without merging**
